- name: Create bin
  ansible.builtin.file:
    path: "{{ bin_dir }}"
    state: directory

- name: template Ansible
  ansible.builtin.template:
    src: "{{ install_Ansible }}.j2"
    dest: "{{ install_Ansible_path }}"
    mode: '0755'

- name: Install Ansible
  ansible.builtin.shell: "distrobox enter {{ container_name_process }} -- sh {{ install_Ansible_path }}"
  async: 3600
  poll: 15